services:
  - type: web
    name: ai-bot-engine
    runtime: docker
    plan: free
    healthCheckPath: /
    dockerfile: ./Dockerfile
    dockerContext: .
    
    # Environment variables
    envVars:
      - key: GOOGLE_GEMINI_API_KEY
        scope: run
        sync: false
      - key: GOOGLE_IMAGEN_API_KEY
        scope: run
        sync: false
      - key: HUGGINGFACE_API_KEY
        scope: run
        sync: false

databases:
  - name: ai-bot-data
    databaseName: ai_bot_data
    user: render
    plan: free
